---
- name: Playbook that targets hosts
  hosts: planet-express
  gather_facts: yes ## runs in the background; logs in diff places.

  tasks:
          - name: Install figlet
            apt:
                    name: figlet
                    state: present  ## can have diff values present, latest, absent and etc..
            become: yes
            when: ansible_os_family == "Debian" ## runs only if the os level is Debian, won't run on other OS

          - name: Install figlet
            yum:
                    name: figlet
                    state: present
            become: yes
            when: ansible_os_family == "RedHat"
          
          - name: issue a command
            command: ls /home
            become: yes
            register: homevarz

          - name: display homevarz  
            debug:
                    var: homevarz
          - name: display the value of homevarz.stdout          
            debug:
                    var: homevarz.stdout

          - name: Place a readme in target systems
            copy:
                    dest: "/home/{{ homevarz.stdout }}/readme.txt"
                    content: "Type figlet to enter the banner creation tool"

